cleanPrometheusOperatorObjectNames: true
fullnameOverride: monitoring

crds:
  enabled: true

defaultRules:
  create: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.demo.ddash.cz
    pathType: Prefix
    tls:
      - hosts:
          - prometheus.demo.ddash.cz
        secretName: prometheus-ingress-tls

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    replicas: 2

    retention: 2d
    retentionSize: 40GiB

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - alertmanager.demo.ddash.cz
    tls:
      - hosts:
          - alertmanager.demo.ddash.cz
        secretName: alertmanager-ingress-tls

grafana:
  adminPassword: admin

  defaultDashboardsEnabled: false

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.demo.ddash.cz
    tls:
      - hosts:
          - grafana.demo.ddash.cz
        secretName: grafana-ingress-tls
